# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: test-workflow

on:
  push:
    branches: [ users_api_endpoints ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    steps:
      - name: Build container
        run: docker-compose up -d --build
      - name: Test
        run: docker-compose exec api python -m pytest "src/tests"
