# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: test-workflow

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Build container
        run: sh "ls"
      - name: Test
        run: docker-compose exec api python -m pytest "src/tests"
